### ISSUE TITLE
url not changing after pressing back button

### ISSUE THREAD

**Issue by abhishekgoel137** [thybag/PJAX-Standalone#3]
Go to http://userbag.co.uk/demo/pjax/page3.php then click on "this link" the link in the body of that page "this link" refers to http://userbag.co.uk/demo/pjax/page2.php. After clicking "this link" press back button. you will reach on page 3 again. Now again click on "this link"  in the body of page 3 you will get the content of page 2 but the url will still show page3

**Comment by linhuiw** [comment]
which browers an versions do you use??

I did the same operating at chrome 28 , It's ok .

**Comment by abhishekgoel137** [comment]
I am also viewing on chrome 28
Please try once again 
step1 : click on  http://userbag.co.uk/demo/pjax/page3.php
step2 : click on the link "this link" in the body of page3.php url will change to page2.php
step3 : click on back button ( you will reach on page3.php
step4 : click on the link "this link" again in the body of page3.php but this time url will not change only content will change

It seems its not storing the history properly

**Comment by alvintran** [comment]
Hi @abhishekgoel137, this link may be useful for you https://gist.github.com/alvintran/6052099

**Comment by thybag** [comment]
Hello,

Sorry about the slow turn around on this one, only just found time to put in a fix. 

The bug was essentially down to how the parseLinks method (which runs every time a page is loaded; to connect up all the links) was being run. I'd initially just been passing it the same options as were used to load the page, the problem then being that when a page was loaded as a result of the back button (which is set not to log in to history), it was connecting up all the links with the same setting. Which is why that link went wonky after the use of a back button.

Will try and upload an updated version of the demo some time this evening :)

Thanks for the report,
Carl

**Comment by abhishekgoel137** [comment]
Thnakyou so much :)

Regards
Abhishek Goel

**Comment by abhishekgoel137** [comment]
I am still waiting for the updated version

Regards
Abhishek Goel
